
//import static adddrug_window.quantitystat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EGYPT
 */
public class placeorder_window extends javax.swing.JFrame {

    /**
     * Creates new form placeorder_window
     */
    ArrayList<Drug> cos=new ArrayList<>();
    ArrayList<Drug> drug=new ArrayList<>();
    ArrayList<Drug> other=new ArrayList<>();
    ArrayList<client> clientt= new ArrayList<>();

    static int quantitystat;
    double total_price=0;
    public static double total_price_static_profit=0;
    public placeorder_window(ArrayList<Drug> cos,ArrayList<Drug>drug ,ArrayList<Drug>other ,int quantitystat, ArrayList<client>clientt) {
        this.cos=cos;
        this.drug=drug;
        this.other=other;
        this.quantitystat=quantitystat;
        this.clientt=clientt;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        drugs_button = new javax.swing.JButton();
        cosmetics_button = new javax.swing.JButton();
        other_button = new javax.swing.JButton();
        name_text = new javax.swing.JTextField();
        id_text = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        quantity_text = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name :");

        drugs_button.setBackground(new java.awt.Color(51, 153, 255));
        drugs_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drugs_button.setText("Show the drugs in the pharmacy");
        drugs_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugs_buttonActionPerformed(evt);
            }
        });

        cosmetics_button.setBackground(new java.awt.Color(51, 153, 255));
        cosmetics_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cosmetics_button.setText("Show the cosmetics in the pharmacy");
        cosmetics_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosmetics_buttonActionPerformed(evt);
            }
        });

        other_button.setBackground(new java.awt.Color(51, 153, 255));
        other_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        other_button.setText("Show the other drugs in the pharmacy");
        other_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                other_buttonActionPerformed(evt);
            }
        });

        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 204, 204));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart.png"))); // NOI18N
        submit.setText("add to the cart");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(other_button)
                    .addComponent(cosmetics_button, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugs_button, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(drugs_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cosmetics_button)
                .addGap(12, 12, 12)
                .addComponent(other_button)
                .addGap(25, 25, 25))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String name=name_text.getText();
        int quantity_of_the_order=Integer.parseInt(quantity_text.getText());
        String id_of_the_order=id_text.getText();
        Place_order order = new Place_order();
        
        try{
        if (id_of_the_order.startsWith("dr")){
            double f_price= order.price(id_of_the_order,quantity_of_the_order ,drug);
            total_price+=f_price;
            total_price_static_profit+=f_price;
            if (f_price!=0){
            adddrug_window.quantitystat-=quantity_of_the_order;
            JOptionPane.showMessageDialog(null, "the total price of "+name+" is= "  +f_price,"L.E", JOptionPane.INFORMATION_MESSAGE);
            }
        }
            else if(id_of_the_order.startsWith("co")){
            double f_price= order.price(id_of_the_order,quantity_of_the_order ,cos);
            total_price+=f_price;
            total_price_static_profit+=f_price;
            if (f_price!=0){
            adddrug_window.quantitystat-=quantity_of_the_order;
            JOptionPane.showMessageDialog(null, "the total price of "+name+" is= "  +f_price,"L.E", JOptionPane.INFORMATION_MESSAGE);
            }     
        }
            else {
            double f_price= order.price(id_of_the_order,quantity_of_the_order ,other);
            total_price+=f_price;
            total_price_static_profit+=f_price;
            if (f_price!=0){
            adddrug_window.quantitystat-=quantity_of_the_order;
            JOptionPane.showMessageDialog(null, "the total price of "+name+" is= "  +f_price,"L.E", JOptionPane.INFORMATION_MESSAGE);
            }
            }
}
        catch(Exception e){
                JOptionPane.showMessageDialog(null, "THE STOCKS IS EMPTY");
                }
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (total_price!= 0.0){
        JOptionPane.showMessageDialog(null, "THE TOTAL PRICE OF YOUR ORDER: "+total_price+"L.E", "RECIEPT!!", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        JOptionPane.showMessageDialog(null, "This drug isn't available ", "order not placed !!", JOptionPane.ERROR_MESSAGE);
        }
        check_client_window obj = new check_client_window(clientt, total_price);
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void drugs_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugs_buttonActionPerformed
        // TODO add your handling code here:
        String names="";
        String price="";
        String quantity="";
        StringBuilder messageBuilder = new StringBuilder();
        for (Drug item : drug){
        messageBuilder.append(item.getName()+"  price per piece: "+item.getPrice()+" stock: "+item.getQuantity()).append("\n");
        }
        JOptionPane.showMessageDialog(null,messageBuilder.toString());
//        JOptionPane.showMessageDialog(null,messageBuilder);

    }//GEN-LAST:event_drugs_buttonActionPerformed

    private void cosmetics_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosmetics_buttonActionPerformed
        // TODO add your handling code here:
        String names="";
        String price="";
        String quantity="";
        StringBuilder messageBuilder = new StringBuilder();
        for (Drug item : cos){
        messageBuilder.append(item.getName()+"  price per piece: "+item.getPrice()+" stock: "+item.getQuantity()).append("\n");
        }
        JOptionPane.showMessageDialog(null,messageBuilder.toString());
    }//GEN-LAST:event_cosmetics_buttonActionPerformed

    private void other_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_other_buttonActionPerformed
        // TODO add your handling code here:
        String names="";
        String price="";
        String quantity="";
        StringBuilder messageBuilder = new StringBuilder();
        for (Drug item : other){
        messageBuilder.append(item.getName()+"  price per piece: "+item.getPrice()+" stock: "+item.getQuantity()).append("\n");
        }
        JOptionPane.showMessageDialog(null,messageBuilder.toString());
    }//GEN-LAST:event_other_buttonActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeorder_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeorder_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeorder_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeorder_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeorder_window(null,null,null,0,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cosmetics_button;
    private javax.swing.JButton drugs_button;
    private javax.swing.JTextField id_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_text;
    private javax.swing.JButton other_button;
    private javax.swing.JTextField quantity_text;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
